"""add AI summary and tags to items

Revision ID: 142052e2b2d3
Revises: 2bbc85f58c9d
Create Date: 2026-08-17 13:39:49.253559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142052e2b2d3'
down_revision: Union[str, Sequence[str], None] = '2bbc85f58c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'tags')
    op.drop_column('items', 'summary')
    # ### end Alembic commands ###
