"""add item processing status

Revision ID: 4a06948bdfb4
Revises: 142052e2b2d3
Create Date: 2026-08-18 16:38:41.921783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a06948bdfb4'
down_revision: Union[str, Sequence[str], None] = '142052e2b2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('processing_status', sa.String(length=20), server_default='pending', nullable=False))
    op.create_check_constraint('ck_items_processing_status', 'items', "processing_status IN ('pending', 'processing', 'completed', 'failed')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_items_processing_status', 'items', type_='check')
    op.drop_column('items', 'processing_status')
    # ### end Alembic commands ###
