"""add processing error to items

Revision ID: 5c6c14588067
Revises: 0b1b680b0b80
Create Date: 2026-08-12 16:38:23.665897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6c14588067'
down_revision: Union[str, Sequence[str], None] = '0b1b680b0b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('processing_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'processing_error')
    # ### end Alembic commands ###
